# Generated by Django 3.2.8 on 2021-10-17 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='new',
        ),
    ]
