# Generated by Django 3.2.8 on 2021-10-19 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='short_desc',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
